README.md, server/app.js, server/controllers/authController.js, server/db/dbClient.js, server/graphql/apolloServer.js, server/graphql/resolvers/mutation.js, server/graphql/resolvers/validators.js
In addition to the disabling of auth in dev, this PR also includes some initial data validation logic.
This is because some necessary logic that was already implemented in the the "teo/error-handling" branch was required. So that's where I branched off for this change. 
Just an FYI.
=> Disable Auth Requirements in Dev

frontend/src/components/Header/Header.jsx, frontend/src/components/Header/Header.scss, frontend/src/components/Header/Search.jsx, frontend/src/components/Header/Search.scss, frontend/src/components/MeetingView/MeetingView.scss, frontend/src/index.jsx
=> Restyled community view header (issue 59).

frontend/src/components/AdminView/AdminUploadView/AdminUploadView.jsx, frontend/src/components/AdminView/AdminUploadView/DragAndDrop.jsx, frontend/src/components/AdminView/AdminView.jsx
This PR fixes the missing dependencies compilation warnings.
=> Fix useEffect missing dependencies warnings

frontend/.eslintrc.json
Closes #117. It's a one-line change for a bug fix and it addresses an issue that occurred on the frontend while trying to use ESLint. 
`"es2021": true` is removed from the `frontend/.eslintrc.json` file.
Because this message gets logged and ESLint doesn't work on the frontend:
`Failed to load plugin 'react' declared in 'frontend/.eslintrc.json': Cannot find module 'eslint-plugin-react' Require stack: - /Users/[User]/Documents/CodingProjects/code-for-san-jose/gov-agenda-notifier/__placeholder__.js Referenced from: /Users/[User]/Documents/CodingProjects/code-for-san-jose/gov-agenda-notifier/frontend/.`
- List the use …
=> Removed "es2021" option from the ESLint config for frontend

backend/graphql_api/lambda/graphql/apolloServer.js
require order_number and content_categories in createMeetingItem and updateMeetingItem
Schema validation in backend graphql
The fields are required by backend. If the frontend doesn't pass it, it will error out. …
=> require order_number and content_categories in createMeetingItem and updateMeetingItem

README.md
* Remove deployed version link in readme to prevent confusion. Addresses #133 
Minor readme update to prevent broken link
Remove deployed version link
Deployed version moving to AWS, no longer hosted on heroku
na
na
na
na
na
na
=> update readme deployment link

README.md, backend/agenda_upload_service/lambda/handler.js, docker-compose.yml
So developers can develop with more representative data.
```
curl --form csvfile='@backend/agenda_upload_service/example.csv' -F csvfile=example.csv localhost:3002/upload
{"jsonValue":"CSV Uploaded!"}
```
=> add 'upload' service to docker compose

backend/graphql_api/lambda/db/dbClient.js, backend/graphql_api/lambda/graphql/apolloServer.js, backend/graphql_api/lambda/graphql/resolvers/mutation.js, backend/graphql_api/lambda/graphql/resolvers/validators.js, backend/graphql_api/lambda/migrations/0003-subscriptions-default-timestamps.sql, backend/graphql_api/lambda/package-lock.json, backend/graphql_api/lambda/package.json
Add `createSubscriptions` mutation to create multiple subscription in a single mutation to replace `createSubscription`.
Requested by @anna-kartynnik
pg-format to do build the INSERT string easily.
None.
```
mutation {
createSubscriptions(
phone_number: "16557338222",
email_address: "a@gmail.com",
meetings: [
{
meeting_id:1
meeting_item_id: 1
},
{
meeting_id:2
meeting_item_id: 2
}
]
) {
id
}
}
```
- Link to relevant external …
=> add 'createSubscription' mutation; Part of #101

frontend/src/components/Header/Header.jsx
One-line change
Fixed a typo
It's a bug fix
None
=> Fixed a typo in meeting status.

README.md, backend/graphql_api/lambda/controllers/subscriptionsController.js, backend/graphql_api/lambda/db/dbClient.js, backend/graphql_api/lambda/graphql/apolloServer.js, backend/graphql_api/lambda/graphql/resolvers/mutation.js, backend/graphql_api/lambda/ses/sesClient.js
New feature
* Create a method to send a confirmation email after user signs up (not hooked up yet)
* Add 'confirmEmail' and 'unconfirmEmail' mutation that toggle column in account table to indicate user has confirmed or unconfirmed email.
For double opt in and unsubscribe.
- Link to relevant external …
=> Implement double opt in and unsubscribe

backend/agenda_upload_service/lambda/db/dbClient.js, backend/graphql_api/lambda/db/dbClient.js, backend/graphql_api/lambda/graphql/apolloServer.js, backend/graphql_api/lambda/graphql/resolvers/mutation.js, backend/graphql_api/lambda/graphql/resolvers/validators.js
createSubscription was deprecated.
createSubscriptions is now being used by frontend. https://github.com/codeforsanjose/gov-agenda-notifier/issues/132
=> remove deprecated 'createSubscription' mutation

backend/agenda_upload_service/lambda/db/dbClient.js, backend/graphql_api/lambda/db/dbClient.js, frontend/src/components/Header/Header.jsx, frontend/src/components/MeetingView/AgendaView/AgendaGroup.jsx, frontend/src/components/MeetingView/AgendaView/AgendaItem.jsx, frontend/src/components/MeetingView/AgendaView/AgendaView.jsx, frontend/src/components/MeetingView/MeetingView.jsx, frontend/src/components/MeetingView/MeetingView.scss, frontend/src/graphql/graphql.js, frontend/src/utils/timestampHelper.js
New feature + bug fix
The details of a meeting is fetched from the backend now. `MeetingView` and related components are changed to render the corresponding data. This PR implements #88. Additionally this PR fixes #144.
Issues #88 and #144.
Rendering of agenda items of a meeting
Error message is shown to a user if it is not empty.
- …
=> Fetching meeting details from the backend

frontend/src/components/MeetingView/AgendaView/AgendaGroup.scss, frontend/src/components/MeetingView/AgendaView/AgendaItem.jsx, frontend/src/components/MeetingView/AgendaView/AgendaItem.scss, frontend/src/constants/MeetingItemStates.js
New feature
Subscribe link in the agenda item is disabled now for items in statuses 'completed' and 'in progress'.
:arrow_right: Issue #99.
People shouldn't be able to subscribe to items which are in progress or completed.
Manually
https://user-images.githubusercontent.com/15210801/111726923-16a5 …
=> Disabled Subscribe link for completed and in progress meeting items (issue 99)

backend/graphql_api/lambda/graphql/apolloServer.js
Bug fix
Fixed typo
:arrow_right: See issue #151.
=> Issue #151: fixed typo.

backend/agenda_upload_service/lambda/controllers/uploadController.js, backend/agenda_upload_service/lambda/db/dbClient.js, backend/agenda_upload_service/lambda/routes/index.js
Adds a new route to upload service which takes in a `meetingId`. This is to allow admins to clear out and add new meeting items to that particular meeting.
There's no validation in the upload service as to who can upload to which meeting. We need to create authorization rules in the upload service which is out of scope for this PR.
```
curl --form csvfile='@backend/agenda_upload_service/example.csv' -F csvfile=example.csv localhost:3002/upload
{"jsonValue":"CSV Uploaded!"}
curl -X PUT --form csvfile='@backend/agenda_upload_service/example.csv' -F csvfile=example.csv localhost:3002/upload/1 …
```
=> Closes #145: add new route /upload/:meetingId in upload service

backend/agenda_upload_service/lambda/db/dbClient.js, backend/graphql_api/lambda/db/dbClient.js
Closes #142 
[Parameterizes the strings we use to query the PostgreSQL database to help prevent SQL injection.](https://node-postgres.com/features/queries#Parameterized%20query)
`backend/graphql_api/lambda/db/dbClient.js`
`backend/agenda_upload_service/lambda/db/dbClient.js`
In these two files, any SQL query strings composed with ECMAScript 6 string interpolation were modified. Also, the `query` constant in each file was changed to accept extra arguments.
Using ES6 interpolation to feed a SQL query string makes it easy for an end user to compose SQL. End users should not be composing SQL.
- List the use cases and edge …
=> Parameterize query strings without interpolation

frontend/public/locales/en/translation.yaml, frontend/public/locales/es/translation.yaml, frontend/public/locales/vi/translation.yaml, frontend/src/components/Footer/Footer.jsx
This PR build upon [PR#130](https://github.com/codeforsanjose/gov-agenda-notifier/pull/130) and adds new `.yaml` translation files in `/frontend/public/locales` for Spanish and Vietnamese. The credit of this PR goes to Zuhair Imaduddin and his translators.
Adds new `.yaml` translation files in `/frontend/public/locales` for Spanish and Vietnamese.
To finalize this [PR#130](https://github.com/codeforsanjose/gov-agenda-notifier/pull/130).
To learn how to switch languages refer to `/frontend/src/components/Footer/Footer.jsx` or …
=> Adds Spanish and Vietnamese Translations

frontend/public/locales/es/translation.yaml, frontend/public/locales/vi/translation.yaml
Fixes the syntactic issues with Vietnamese and Spanish yaml translation files introduced in PR#165. Please test this PR in your local dev machine to make sure you're seeing the languages being switched.
Fixed a wrong indentation and the wrong use of a colon(:) sign in the Spanish yaml file and removed an unnecessary translation for a key in the Vietnamese file. 
To fix language switching functionality.
It'll be used to switch between different languages.
Refer to the …
=> fixed the issue with languages not being switched

backend/graphql_api/lambda/graphql/apolloServer.js
=> Fixed a typo with Roles enum.

.github/workflows/aws.yml, backend/graphql_api/lambda/Dockerfile, docker-compose.yml, frontend/Dockerfile, frontend/nginx/default.conf, frontend/nginx/nginx.conf, frontend/src/index.jsx
=> Dockerfilize for deployment

README.md
Adding environment variables to ReadMe
Added the following environment variables to ReadMe
JWT_SECRET = NEED-TO_CREATE-SECRET-KEY
JWT_ISSUER = ADD-ISSUER-DOMAIN
JWT_AUDIENCE = ADD-AUDIENCE
GOOGLE_CLIENT_ID = NEED-TO-REGISTER-APP
GOOGLE_CLIENT_SECRET = NEED-TO-REGISTER-APP
- Link to relevant external …
=> Added new enviroment variables to ReadMe

frontend/src/graphql/graphql.js
Bug fix
Renamed parameters (`item_start_timestamp`, `item_end_timestamp`) changed in #160 in frontend's GraphQL query.
To fix a bug
=> Fixed frontend graphql query after some parameters have been renamed

backend/graphql_api/lambda/db/dbClient.js, backend/graphql_api/lambda/graphql/apolloServer.js, backend/graphql_api/lambda/graphql/resolvers/mutation.js, backend/graphql_api/lambda/migrations/0006-parent-meeting-item-fk.sql
New feature
I've added 'parent_meeting_item_id' to `createMeetingItem` and `updateMeetingItem`. I've also added a corresponding foreign key for the db scheme. 
Implements issue #149.
Now it's possible to create meeting items in hierarchical structure. …
=> Added 'parent_meeting_item_id' to createMeetingItem and updateMeetingItem

backend/graphql_api/lambda/migrations/0007-meeting-item-fk.sql
Just a DB schema change. No code change.
Add DB migration to add a foreign key for meeting_item_id.
Closes https://github.com/codeforsanjose/gov-agenda-notifier/issues/194
- PR = …
=> Add a foreign key for meeting_item_id

backend/graphql_api/lambda/migrations/0008-meeting-fk-on-delete-cascade.sql
=> Last migration fix.

docker-compose.yml
=> Added http part to REACT_APP_GRAPHQL_URL env variable

frontend/src/components/UserAccountView/UserAccountUpdateView.jsx, frontend/src/components/UserAccountView/UserAccountView.jsx, frontend/src/components/UserAccountView/UserAccountView.scss
-- Add components for the User Account View
-- Created 2 Components, UserAccountView which will show the User's info (First Name, Last Name, Email, Phone, Reset Password) and UserAccountViewUpdate which will also show the User's info but in an Editable way.
-- Changes are being made to allow Users to see their info and make changes if needed.
-- Any User will be able to use this. 
-- Need to add input checkers (sanitization) for User account editing. 
- Describe any external …
=> Add components for UserAccountView and UserAccountUpdateView for Frontend

backend/graphql_api/lambda/db/dbClient.js, backend/graphql_api/lambda/graphql/apolloServer.js, backend/graphql_api/lambda/graphql/resolvers/mutation.js, backend/graphql_api/lambda/graphql/resolvers/validators.js, frontend/src/components/MeetingView/ParticipateView/ParticipateView.jsx, frontend/src/components/Subscribe/Subscribe.jsx, frontend/src/components/Subscribe/subscribeQueryString.js, frontend/src/index.jsx, frontend/src/utils/verifyToken.js
New feature.
`meeting_id` is removed from subscription creation function (from both frontend and backend). Also now users can subscribe to either text or email notifications or both of them.
Issues #193, #195, #218.
Use subscribes to agenda items using phone, email or both of them.
Errors from the server are shown on the page.
n/a
n/a
- …
=> Changes with subscriptions

README.md
Documentation only: update to Resources section of project ReadMe to add link for Project User Story Board on Miro.
Documentation only: update to Resources section of project ReadMe to add link for Project User Story Board on Miro.
To consolidate onboarding process of new members such that all core project docs are centralized in project ReadMe
N/A: Documentation only
N/A: Documentation only
N/A: …
=> Add Miro project board link to Resources Section

frontend/src/components/LoginHandler/LoginHandler.jsx, frontend/src/components/LoginHandler/LoginHandler.scss
make login page responsive
Changes primarily comprise media query updates to the Sass stylesheet (scss file) with one minor update to the jsx file to accommodate different location of "forgot password" link on mobile.   Also added highlighting/brightening of buttons on hover which is similar behavior to elsewhere within the app (e.g. when hovering over meeting view 'agenda' and 'participate' buttons).  
As suggested by Annie S., I held off on adding the city logo as an official dark version logo for mobile view has not yet been identified/provided by design team.  Similarly did not add create account feature as that is not in the the scope of this issue.
Note, …
=> make login page responsive

frontend/public/locales/en/translation.yaml, frontend/src/components/CustomInput/CustomInput.jsx, frontend/src/components/CustomInput/CustomInput.scss, frontend/src/components/Subscribe/Subscribe.jsx, frontend/src/components/Subscribe/validation.js
New feature
Added a mask for phone number field and a note that we only support US phone numbers.
Issue #230.
https://user-images.githubusercontent.com/15210801/125177433-8225fd00-e190-11eb-8be7-89f4b812888b …
=> Added a mask and a note that we support only US phone numbers.

frontend/src/components/MeetingListView/MeetingListItem.jsx
Meeting list now shows the actions specific for admins.
Issue #164
We had identical actions for all users
Now admins can see other actions
=> Show admin links in meeting list (for admins).

frontend/src/components/MeetingListView/MeetingListView.scss
for mobile and browser responsiveness, replaced depecrated setting
"min-device-width" with min-width.  fixes issue with browser resizing
fixing browser resizing issue reported by team (product manager)
minor 'typo' edit to 2 lines of code in scss stylesheet only.  Issue: mobile-responsive css styling is using a deprecated setting of “min-device-width” as opposed to “min-width”.  replaced with new min-width setting.  Note, upon further review, this issue appears to be prevalent throughout existing codebase and deserves a separate PR for fixing throughout the application (i.e. search and replacing all such instances and retesting accordingly).
- Describe why …
=> fix browser resizing issue

backend/agenda_upload_service/lambda/app.js, backend/agenda_upload_service/lambda/package-lock.json, backend/agenda_upload_service/lambda/package.json
fix to csv Agenda upload service
add required support for Cross Origin Requests (CORs) in order for csv uploads to work
As the csv upload is it's own Express app (separate Express server instance from main App), cross origin requests need to be supported in order for admins to be able to upload csv files on the main happening-ATM app.
admin uploading of csv agenda files
N/A
CORs dependency added to …
=> Csv Agenda upload fix for CORs support

frontend/public/locales/en/translation.yaml, frontend/src/components/MeetingView/AgendaView/AgendaItem.jsx, frontend/src/components/MeetingView/AgendaView/AgendaItem.scss, frontend/src/components/Subscribe/SubscribeConfirmation.jsx, frontend/src/utils/_colors.scss
If status of item is completed, it will show completed.
If status of item is deferred, it will show deferred.
If item is subscribed, it will show subscribed.
If item is not yet subscribed, it will show notify me.
If item is subscribing, it will show susbscribing.
- Link to relevant external …
=> edit styling for "notify me" btn

backend/graphql_api/lambda/db/dbClient.js, backend/graphql_api/lambda/graphql/apolloServer.js, backend/graphql_api/lambda/graphql/resolvers/mutation.js, backend/graphql_api/lambda/graphql/resolvers/query.js, backend/graphql_api/lambda/ses/sesClient.js, frontend/package-lock.json, frontend/public/locales/en/translation.yaml, frontend/public/locales/es/translation.yaml, frontend/public/locales/vi/translation.yaml, frontend/src/components/ForgotPassword/ForgotPasswordRequest.jsx, frontend/src/components/ForgotPassword/ForgotPasswordRequest.scss, frontend/src/components/ForgotPassword/SetNewPassword.jsx, frontend/src/components/LoginHandler/LoginHandler.jsx, frontend/src/graphql/graphql.js, frontend/src/index.jsx
New Feature
1. Added ForgotPassword & SetNewPassword components.
2. Added GraphQL query & mutations Get_Token, update_token and reset_password.
3. Email sent on forgot password request.
https://trello.com/c/XC1mShgs/101-eng-forgot-password
1. User clicks forgot password link.
2. User taken to reset password screen.
3. Cases - User exists in system. Negative - User not registered in system
4. Valid user requests send password reset email.
5. User clicks email link in inbox
6. Email link cases:
valid,
null,
invalid,
expired
7. If valid, user taken to set new …
=> Completed forgot password feature

frontend/src/components/LanguageDropdown/LanguageDropdown.jsx, frontend/src/components/LanguageDropdown/LanguageDropdown.scss, frontend/src/components/NavBarHeader/NavBarHeader.jsx, frontend/src/components/NavBarHeader/NavBarHeader.scss, frontend/src/components/NavBarHeader/NavLinks.jsx, frontend/src/components/NavBarHeader/NavLinks.scss, frontend/src/components/NavBarHeader/NavigationLink.jsx, frontend/src/components/NavBarHeader/NavigationLink.scss, frontend/src/components/NavBarHeader/Signout.jsx, frontend/src/components/NavBarHeader/Signout.scss
https://trello.com/c/Chjs0R0p/108-eng-update-the-contents-in-menu-bar
Update contents in menu bar (mobile view)
In addition to reformatting the contents in menu bar, previously I was using a component "AdminNavigationLinks" for each link item. I thought it belonged with NavBar components, so I created a copy of the AdminNavigationLinks component  into the NavBar component folder and renamed it "NavigationLinks". I also separated signout button into its own component so it's easier to use in different components.
- Describe how errors will be handled. How will we …
=> Update contents in menu bar (mobile view)

README.md
(no code changes here) Just updating project github page with latest url links for documentation purposes - helps to have project github page as central repo w/ latest documentation and links for engineering/project team reference.
Can see exact changes in the 'Commits' tab - just a quick replacement w/ new url link is all.
- Describe how …
=> update w/ latest visual design doc url (new google drive)

README.md
(no code changes here) Just updating project github page with latest url links for documentation purposes - helps to have project github page as central repo w/ latest documentation and links for engineering/project team reference.
Can see exact changes in the 'Commits' tab - just a quick replacement w/ new url link is all.
- Describe how …
=> update google drive link w/ latest & add kanban url

README.md
1. Just changing header level for the section "To Begin Work on the Backend / Serve Backend" such that it has the same heading level as "To Begin Work on the Frontend / Serve Frontend".  This way, it's clear both sections fall under the now deprecated 'Option 2' set up.  Prior to change, that section looked like it's own independent section (e.g. that could be done in combination with Option 1).
2.  Also updated link to visual design mocks (for some reason previous commit didn't work).
- Describe how errors will be handled. How will we know if this code breaks in …
=> updated document formatting for clarity & update w/ latest design doc link

.github/workflows/aws-backend-deploy.yml
- Fix Github action for backend deployment to correct file path for Dockerfile and Docker path
=> Github action - fix backend Dockerfile path

.github/workflows/aws-backend-deploy.yml, .github/workflows/aws-frontend-deploy.yml
Somehow forgot to add the path variable when creating the new Docker images
=> Github action - fix Docker path for creating image

backend/agenda_upload_service/lambda/controllers/uploadController.js
Fix to CSV file Agenda Upload Service to support loading (and subsequent display) of agenda subtitles.
Minor code fix to uploadController.js (found in "backend/agenda_upload_service/lambda/controllers/uploadController.js") such that the CSV file Agenda Upload Service will properly support loading (and subsequent display) of agenda subtitles.  Prior to fix the subtitles would simply be populated with the root meeting item titles (see demo/illustration below for before/after)
In order for app functionality to be in line with design and requirements.  Latest designs can be found here: (see "community member mobile" …
=> upload agenda subtitles

backend/graphql_api/lambda/db/dbClient.js, backend/graphql_api/lambda/graphql/resolvers/authentication.js, frontend/src/utils/verifyToken.js
Bug fixes: to enable notifications of upcoming 'next' agenda item subscriptions as well as sending of SMS texts notifications via Twilio API.
1) Fix for allowing notification to next agenda item subscriptions (was erroring out prior to bug fix): Within backend/graphql_api/lambda/db/dbClient.js replaced sql query argument references with syntax $n (i.e. $1 for first argument) which was erroring out with plain JS template string.   Minor cleanup edits as well (adding missing semi colons)
2) Bug fixes to allow SMS text subscription notifications via Twilio's API: 
a) Within backend/graphql_api/lambda/graphql/resolvers/authentication.js, added user phone number to …
=> Subscribe fixes

README.md, frontend/src/components/UserAccountCreate/AccountCreate.jsx, frontend/src/constants/Recaptchas.js
Adding instructions for setting up the recaptcha for account creation. Also created a constant for the recaptcha.
Modified the readme, and added a file to hold a constant for the account creation recaptcha site key.
So that developers and testers know how to get the account creation feature functioning.
- Describe how you tested these …
=> add create account instructions to readme, and use a constant for the recaptcha

frontend/src/components/MeetingListView/MeetingListItemLinks.jsx, frontend/src/utils/generalStyles.scss
This affects meetings that have already taken place.
Remove the ability to upload new agenda items, or delete those meetings.
Add a style of visibility:hidden to the two links when the meeting is from the past.
https://trello.com/c/MkIbDwww/164-eng-prevent-adding-new-agenda-items-or-deleting-the-agenda-of-past-meetings
- Describe how you …
=> remove adding new items, or deleting a meeting, when the meeting is from the past

frontend/src/components/NavBarHeader/NavBarHeader.jsx, frontend/src/index.jsx
bug fix
Added the link to the profile section
As per the story- https://trello.com/c/laLiStBr/183-eng-link-to-profile-is-not-working
https://trello.com/c/laLiStBr/183-eng-link-to-profile-is-not-working
=> updated profile link functionality-183

docker-compose.yml, frontend/src/components/Footer/Footer.jsx, frontend/src/components/PrivacyPolicy/PrivacyPolicy.jsx, frontend/src/components/SendFeedback/SendFeedback.jsx, frontend/src/index.jsx
New page, bug fix
Updated docker-compose file
Added Send Feedback and Privacy Policy page
Docker-compose file needs to be updated.
- [ x ] Have you discussed these changes with the project leader(s)?
- [ x ] Do all variable and function names communicate what they do?
- [ x ] Were all the changes commented and / or documented?
- [ x ] Is the PR the right size? (If the PR is too large to review, it might be good to break it up into multiple PRs.)
=> updated docker-compose file, added feedback and privacy policy page

frontend/public/index.html
=> changed HTML title

frontend/src/components/Footer/Footer.jsx
bug fix
small syntax change that was causing an error ("class" instead of "className")
small syntax change that was causing an error ("class" instead of "className")
N/A
N/A
N/A
N/A
Docker, Chrome
- [ x] Linked to the Github Issues …
=> fixed syntax that was causing an error

frontend/src/components/AboutUs/AboutUs.scss, frontend/src/components/FAQ/FAQ.scss, frontend/src/components/LoginHandler/LoginHandler.jsx, frontend/src/components/LoginHandler/LoginHandler.scss
**UI changes**
**Edited styling for FAQ, About, and Login pages to match Figma**
**UI polishing**
=> edit styling for faq, about, login pages

frontend/public/locales/en/translation.yaml, frontend/src/components/AdminView/AdminNavigation.jsx, frontend/src/components/AdminView/AdminNavigation/AdminNavigation.jsx, frontend/src/components/CSVUploadModal/CSVUploadModal.jsx, frontend/src/components/CSVUploadModal/CSVUploadModal.scss, frontend/src/components/MeetingListView/MeetingListItem.scss, frontend/src/components/MeetingListView/MeetingListView.scss
**Responsiveness fix for mobile**
**Fixed mobile UI for calendar page**
**Meeting list items break on mobile view**
**UI polishing**
=> landing page responsive

backend/graphql_api/lambda/db/dbClient.js
Patch for PR #320
Changes described by @jerrycyip in #320 discussion.
These changes fix the agenda upload in the create new meeting flow.
Creating a new meeting successfully, including the upload agenda part.
Check to see if you can successfully create a new meeting without errors (must be admin).
1. …
=> Patch for PR #320, Agenda upload in create meeting flow

.github/workflows/aws-backend-deploy.yml, .github/workflows/aws-frontend-deploy.yml
=> Github Actions - update build/deploy workflows

.github/workflows/aws-backend-deploy.yml, .github/workflows/aws-frontend-deploy.yml
=> add region to ecr login

backend/agenda_upload_service/app.js, backend/agenda_upload_service/db/dbClient.js, backend/agenda_upload_service/package-lock.json, backend/agenda_upload_service/package.json, backend/agenda_upload_service/routes/index.js, backend/agenda_upload_service/routes/loginRoute/loginRoute.js, backend/agenda_upload_service/utilities/auth.js, backend/agenda_upload_service/utilities/config.js, backend/graphql_api/db/dbClient.js, backend/graphql_api/graphql/apolloServer.js, backend/graphql_api/graphql/resolvers/authentication.js, backend/graphql_api/graphql/resolvers/mutation.js, backend/graphql_api/graphql/services/authentication.js, backend/graphql_api/graphql/services/fetchingWrapper.js, frontend/src/components/LoginHandler/LoginHandler.jsx, frontend/src/utils/isAdmin.js, frontend/src/utils/parseJwt.js, package-lock.json, package.json
=> Start of refactor login

README.md
**Added Docker build up instructions to the README file, let me know if that's not correct** 
=> Docker info

backend/agenda_upload_service/controllers/uploadController.js, backend/agenda_upload_service/db/dbClient.js, backend/agenda_upload_service/test_data/example.csv
Minor fixes to remove duplicate DB client connections in DBClient and a typo correction to the test csv file for meeting agenda uploads.
Minor fixes to remove duplicate DB client connections in DBClient and a typo correction to the test csv file for meeting agenda uploads.
1) code change to dbClient.js (i.e. backend/agenda_upload_service/db/dbClient.js)
* within dbClient.js,  remove “await client.connect()” on line ~21 and the enclosing try/catch statement block from lines ~20 - 26.
* Prior to change (i.e. original code) the agenda upload process resulted in an error on the server side as follows: “DB connection error: Error: Client has already been connected. …
=> Patch to csv agenda upload functionality

backend/agenda_upload_service/db/dbClient.js, backend/agenda_upload_service/routes/loginRoute/loginRoute.js, backend/graphql_api/db/dbClient.js, backend/graphql_api/graphql/apolloServer.js, backend/graphql_api/graphql/services/authentication.js, frontend/src/index.jsx, frontend/src/utils/parseJwt.js
Fix login/authentication functionality in frontend and backend.
1. Frontend/src/index.jsx: Fix un-necessary errors that prevent log in functionality and showed up in the browser developer console.  (i) The code originally attempted to verify/parse the user token when none existed because the user was not yet logged in, and also (ii) the code incorrectly expected a boolean (true) rather than a string value (i.e. "true") when retrieving the token from window.localStorage.getItem(LocalStorageTerms.SIGNED_IN).
2. Frontend/src/utils/parseJwt.js.  Fixes for restoring proper parsing logic of JSON Web Token (JWT).  Note, as an alternative to the parsing logic added, …
=> Authentication patch

charts/happeningatm/templates/_ingress.yaml
- Different requests based on path should go to different services (graphql or backend node) 
- Update nginx ingress yaml
- DNT
=> nginx pathing updates

docker-bake.hcl, docker-compose.yml
- Patch to fix build of docker container image for local frontend development environment.
- Updates to docker-bake.hcl and docker-compose.yaml files to ensure docker container image for local frontend dev server is built out properly
- Prior to change the local development front end server was not starting up properly and consequently the frontend app (i.e. at http://localhost:3001) was not accessible (e.g. user sees a 404 error when accessing app in the browser).
- Need to access local dev envmt to work on coding front end fixes/features.
- Describe how errors …
=> patch to fix local dev enmt frontend server

frontend/public/locales/en/translation.yaml, frontend/public/locales/es/translation.yaml, frontend/public/locales/vi/translation.yaml, frontend/src/components/BackNavigation/BackNavigation.scss, frontend/src/components/MeetingView/MeetingView.jsx, frontend/src/components/NavBarHeader/HamburgerIcon.scss, frontend/src/components/NavBarHeader/NavBarHeader.jsx, frontend/src/components/NavBarHeader/NavBarHeader.scss, frontend/src/components/NavBarHeader/NavLinks.jsx, frontend/src/components/NavBarHeader/NavLinks.scss, frontend/src/components/NavBarHeader/NavigationLink.scss
UI layout and styling fixes to more closely match latest [MVP Figma designs](https://www.figma.com/file/MEBv8hZLr4MICzKCVXADjg/Happening-ATM?type=design&node-id=6150-89385&mode=design&t=MUrNihqnqLZxeWvr-0).
* UI layout and styling fixes to more closely match latest [MVP Figma designs] (https://www.figma.com/file/MEBv8hZLr4MICzKCVXADjg/Happening-ATM?type=design&node-id=6150-89385&mode=design&t=MUrNihqnqLZxeWvr-0).  These changes comprise the following:
* Issues with the navigation bar at the top of the application on desktop and tablet views:
* Navigation bar shows all menu icon options rather than central hamburger menu icon (e.g. My City’s Agenda, FAQ, About …
=> UI layout and styling fixes

README.md
=> updated needed readme changes
